version: '3.8'

services:
  backend:
    image: 192.168.252.114:8083/nodemongoapp-backend:5.0
    container_name: nodemongoapp-backend
    restart: always
    ports:
      - "8089:8089"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    image: 192.168.252.114:8083/nodemongoapp-frontend:5.0
    container_name: nodemongoapp-frontend
    restart: always
    ports:
      - "3000:3000"

  db:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db

volumes:
  mongo-data:
