version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 192.168.252.114:8083/nodemongoapp:5.0
    container_name: nodemongoapp
    restart: always
    ports:
      - "3000:3000"
      - "8089:8089"
    env_file:
      - ./backend/.env
